/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "primary": "var(--primary)",
        "on-primary-fixed-variant": "var(--on-primary-fixed-variant)",
        "outline": "var(--outline)",
        "on-secondary-container": "var(--on-secondary-container)",
        "on-tertiary-fixed-variant": "var(--on-tertiary-fixed-variant)",
        "primary-fixed": "var(--primary-fixed)",
        "error": "var(--error)",
        "surface-tint": "var(--surface-tint)",
        "surface-container": "var(--surface-container)",
        "warning-text": "var(--warning-text)",
        "inverse-surface": "var(--inverse-surface)",
        "tertiary-container": "var(--tertiary-container)",
        "primary-container": "var(--primary-container)",
        "page-bg": "var(--page-bg)",
        "on-primary-container": "var(--on-primary-container)",
        "outline-variant": "var(--outline-variant)",
        "secondary-fixed-dim": "var(--secondary-fixed-dim)",
        "on-primary": "var(--on-primary)",
        "surface-container-highest": "var(--surface-container-highest)",
        "on-surface": "var(--on-surface)",
        "on-tertiary": "var(--on-tertiary)",
        "success-bg": "var(--success-bg)",
        "tertiary": "var(--tertiary)",
        "error-container": "var(--error-container)",
        "background": "var(--background)",
        "primary-fixed-dim": "var(--primary-fixed-dim)",
        "on-surface-variant": "var(--on-surface-variant)",
        "on-primary-fixed": "var(--on-primary-fixed)",
        "surface-container-low": "var(--surface-container-low)",
        "inverse-primary": "var(--inverse-primary)",
        "tertiary-fixed": "var(--tertiary-fixed)",
        "tertiary-fixed-dim": "var(--tertiary-fixed-dim)",
        "success-text": "var(--success-text)",
        "danger-bg": "var(--danger-bg)",
        "on-background": "var(--on-background)",
        "on-tertiary-container": "var(--on-tertiary-container)",
        "border-hairline": "var(--border-hairline)",
        "surface-dim": "var(--surface-dim)",
        "surface-bright": "var(--surface-bright)",
        "surface-container-lowest": "var(--surface-container-lowest)",
        "on-tertiary-fixed": "var(--on-tertiary-fixed)",
        "on-secondary-fixed": "var(--on-secondary-fixed)",
        "on-secondary-fixed-variant": "var(--on-secondary-fixed-variant)",
        "warning-bg": "var(--warning-bg)",
        "on-secondary": "var(--on-secondary)",
        "surface": "var(--surface)",
        "secondary-fixed": "var(--secondary-fixed)",
        "inverse-on-surface": "var(--inverse-on-surface)",
        "on-error-container": "var(--on-error-container)",
        "secondary-container": "var(--secondary-container)",
        "surface-container-high": "var(--surface-container-high)",
        "secondary": "var(--secondary)",
        "surface-variant": "var(--surface-variant)",
        "on-error": "var(--on-error)",
        "surface-panel": "var(--surface-panel)",
        "danger-text": "var(--danger-text)"
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px"
      },
      spacing: {
        gutter: "0.75rem",
        "space-xs": "0.5rem",
        margin: "1.5rem",
        "space-md": "1rem",
        "space-lg": "1.5rem",
        "space-sm": "0.75rem",
        "space-xl": "2rem"
      },
      fontFamily: {
        "code-sm": ["JetBrains Mono", "monospace"],
        "headline-h2": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "headline-h1": ["Inter", "sans-serif"],
        "metric-number": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        sans: ["Inter", "sans-serif"],
        mono: ["JetBrains Mono", "monospace"],
      },
      fontSize: {
        "code-sm": ["13px", { lineHeight: "18px", fontWeight: "400" }],
        "headline-h2": ["18px", { lineHeight: "24px", fontWeight: "500" }],
        "label-sm": ["12px", { lineHeight: "16px", fontWeight: "400" }],
        "label-md": ["13px", { lineHeight: "16px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-h1": ["22px", { lineHeight: "28px", fontWeight: "500" }],
        "metric-number": ["24px", { lineHeight: "32px", fontWeight: "500" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }]
      }
    }
  },
  plugins: [],
}
